name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Build
      run: go build -v -trimpath -tags "ts_omit_systray,ts_omit_webclient,ts_omit_webbrowser,ts_omit_qrcodes,ts_omit_colorable,ts_omit_desktop_sessions,ts_omit_completion,ts_omit_completion_scripts,ts_omit_drive" -ldflags="-s -w" ./cmd/tunnneji-tail
